const STORAGE_KEY='asmrtube.library.v1';
const DEFAULT_TAGS=['耳かき','梵天','囁き','吐息','オノマトペ','タッピング','マッサージ','添い寝','ロールプレイ','睡眠'];
const EAR_TAGS=['右耳','左耳','両耳','交互'];
const state={library:[],playlists:[],recent:[],selectedId:null,currentView:'all',currentPlaylist:null,query:'',filters:new Set(),player:null,currentId:null,duration:0,loopA:null,loopB:null,sleepTimer:null,parsedTimestamps:[]};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify({library:state.library,playlists:state.playlists,recent:state.recent}))}
function load(){try{const d=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');state.library=Array.isArray(d.library)?d.library:[];state.playlists=Array.isArray(d.playlists)?d.playlists:[];state.recent=Array.isArray(d.recent)?d.recent:[]}catch{toast('保存データを読み込めませんでした')}}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function ytId(url){try{const u=new URL(url.trim());if(u.hostname.includes('youtu.be'))return u.pathname.slice(1).split('/')[0];if(u.hostname.includes('youtube.com')){if(u.pathname.startsWith('/shorts/'))return u.pathname.split('/')[2];return u.searchParams.get('v')}}catch{}const m=String(url).match(/(?:v=|youtu\.be\/|shorts\/)([\w-]{11})/);return m?.[1]||null}
function thumb(id){return id?`https://i.ytimg.com/vi/${id}/hqdefault.jpg`:''}
function fmt(sec){sec=Math.max(0,Math.floor(Number(sec)||0));const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`}
function parseTime(t){const p=t.split(':').map(Number);if(p.some(Number.isNaN))return null;if(p.length===2)return p[0]*60+p[1];if(p.length===3)return p[0]*3600+p[1]*60+p[2];return null}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2200)}
function ratingLabel(n){return ['未評価','普通','好き','かなり好き','神'][Number(n)||0]}
function tagList(v){return String(v||'').split(/[,、]/).map(s=>s.trim()).filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i)}
function allTags(){return [...new Set([...DEFAULT_TAGS,...EAR_TAGS,...state.library.flatMap(x=>x.tags||[])])].sort((a,b)=>a.localeCompare(b,'ja'))}
function itemById(id){return state.library.find(x=>x.id===id)}
function renderFilterChips(){const ear=$('#earFilters'),type=$('#typeFilters');ear.innerHTML=EAR_TAGS.map(tag=>chipHtml(tag)).join('');type.innerHTML=allTags().filter(t=>!EAR_TAGS.includes(t)).map(tag=>chipHtml(tag)).join('');$$('.filter-chip').forEach(b=>b.onclick=()=>{state.filters.has(b.dataset.tag)?state.filters.delete(b.dataset.tag):state.filters.add(b.dataset.tag);renderFilterChips();renderLibrary()})}
function chipHtml(tag){return `<button class="chip filter-chip ${state.filters.has(tag)?'active':''}" data-tag="${esc(tag)}">${esc(tag)}</button>`}
function filtered(){let a=[...state.library];if(state.currentView==='favorites')a=a.filter(x=>x.favorite);if(state.currentView==='recent')a=state.recent.map(id=>itemById(id)).filter(Boolean);if(state.currentView==='sleep')a=a.filter(x=>x.sleepFriendly||x.tags?.includes('睡眠'));if(state.currentView==='playlist'){const p=state.playlists.find(p=>p.id===state.currentPlaylist);a=(p?.items||[]).map(id=>itemById(id)).filter(Boolean)}if(state.query){const q=state.query.toLowerCase();a=a.filter(x=>[x.title,x.creator,...(x.tags||[])].join(' ').toLowerCase().includes(q))}if(state.filters.size)a=a.filter(x=>[...state.filters].every(t=>x.tags?.includes(t)));const s=$('#sortSelect').value;if(s==='title')a.sort((x,y)=>x.title.localeCompare(y.title,'ja'));else if(s==='rating')a.sort((x,y)=>(y.rating||0)-(x.rating||0));else if(state.currentView!=='recent')a.sort((x,y)=>(y.createdAt||0)-(x.createdAt||0));return a}
function renderLibrary(){const a=filtered();$('#resultCount').textContent=`${a.length}件`;$('#libraryGrid').innerHTML=a.map(cardHtml).join('');$('#emptyState').classList.toggle('hidden',a.length>0);$$('.card').forEach(c=>c.onclick=e=>{if(e.target.closest('.fav'))return;state.selectedId=c.dataset.id;renderLibrary();renderDetail()});$$('.fav').forEach(b=>b.onclick=e=>{e.stopPropagation();const x=itemById(b.dataset.id);x.favorite=!x.favorite;save();renderLibrary();if(state.selectedId===x.id)renderDetail()})}
function cardHtml(x){return `<article class="card ${state.selectedId===x.id?'active':''}" data-id="${x.id}"><div class="thumb"><img src="${thumb(x.videoId)}" alt=""><button class="fav" data-id="${x.id}" title="お気に入り">${x.favorite?'★':'☆'}</button></div><div class="card-body"><div class="card-title">${esc(x.title)}</div><div class="card-meta">${esc(x.creator||'配信者未設定')}</div><div class="tag-row">${(x.tags||[]).slice(0,4).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="rating">${ratingLabel(x.rating)}</div></div></article>`}
function renderDetail(){const x=itemById(state.selectedId);if(!x){$('#detailPanel').innerHTML='<div class="detail-empty">カードを選ぶと詳細を表示します</div>';return}$('#detailPanel').innerHTML=`<div class="detail-hero"><img src="${thumb(x.videoId)}" alt=""></div><h2 class="detail-title">${esc(x.title)}</h2><div class="detail-creator">${esc(x.creator||'配信者未設定')}</div><div class="tag-row">${(x.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="detail-actions"><button id="detailPlay">▶ 再生</button><button id="detailFav">${x.favorite?'★':'☆'} お気に入り</button><button id="detailTs">時刻コメント取込</button><button id="detailEdit">編集</button><button id="detailPlaylist">プレイリストへ</button><button id="detailDelete" class="danger">削除</button></div><div class="section-head"><strong>タイムスタンプ</strong><span>${(x.timestamps||[]).length}件</span></div><div class="timestamps">${(x.timestamps||[]).sort((a,b)=>a.time-b.time).map((t,i)=>`<div class="ts-row"><button class="ts-time" data-time="${t.time}">${fmt(t.time)}</button><div><div>${esc(t.label)}</div><div class="tag-row">${(t.tags||[]).map(z=>`<span class="tag">${esc(z)}</span>`).join('')}</div></div><button class="ts-del" data-index="${i}">×</button></div>`).join('')||'<div class="detail-empty">まだタイムスタンプがありません</div>'}</div>`;$('#detailPlay').onclick=()=>playItem(x.id);$('#detailFav').onclick=()=>{x.favorite=!x.favorite;save();renderLibrary();renderDetail()};$('#detailTs').onclick=()=>openTimestampDialog();$('#detailEdit').onclick=()=>openVideoDialog(x);$('#detailPlaylist').onclick=()=>addToPlaylistPrompt(x.id);$('#detailDelete').onclick=()=>{if(!confirm('このASMRを削除しますか？'))return;state.library=state.library.filter(v=>v.id!==x.id);state.playlists.forEach(p=>p.items=p.items.filter(id=>id!==x.id));state.recent=state.recent.filter(id=>id!==x.id);state.selectedId=null;save();renderAll()};$$('.ts-time').forEach(b=>b.onclick=()=>{playItem(x.id,Number(b.dataset.time))});$$('.ts-del').forEach(b=>b.onclick=()=>{x.timestamps.splice(Number(b.dataset.index),1);save();renderDetail()})}
function renderPlaylists(){const box=$('#playlistList');box.innerHTML=state.playlists.map(p=>`<button data-id="${p.id}" class="${state.currentPlaylist===p.id?'active':''}">${esc(p.name)} <span>(${p.items.length})</span></button>`).join('');[...box.children].forEach(b=>b.onclick=()=>{state.currentView='playlist';state.currentPlaylist=b.dataset.id;$$('.nav-btn').forEach(n=>n.classList.remove('active'));$('#viewTitle').textContent=state.playlists.find(p=>p.id===b.dataset.id)?.name||'プレイリスト';$('#viewSub').textContent='プレイリスト内のASMR';renderPlaylists();renderLibrary()})}
function renderAll(){renderPlaylists();renderFilterChips();renderLibrary();renderDetail()}
function openVideoDialog(x=null){$('#videoDialogTitle').textContent=x?'ASMRを編集':'ASMRを追加';$('#editId').value=x?.id||'';$('#videoUrl').value=x?.url||'';$('#videoTitle').value=x?.title||'';$('#creator').value=x?.creator||'';$('#tags').value=(x?.tags||[]).join(', ');$('#rating').value=String(x?.rating||0);$('#itemVolume').value=String(x?.volume??35);$('#sleepFriendly').checked=!!x?.sleepFriendly;$('#videoDialog').showModal()}
function saveVideo(e){e.preventDefault();const url=$('#videoUrl').value.trim(),videoId=ytId(url);if(!videoId)return toast('有効なYouTube URLを入力してください');const editId=$('#editId').value;const dup=state.library.find(x=>x.videoId===videoId&&x.id!==editId);if(dup)return toast(`「${dup.title}」として登録済みです`);const data={url,videoId,title:$('#videoTitle').value.trim(),creator:$('#creator').value.trim(),tags:tagList($('#tags').value),rating:Number($('#rating').value),volume:Math.min(100,Math.max(0,Number($('#itemVolume').value)||35)),sleepFriendly:$('#sleepFriendly').checked};if(editId){Object.assign(itemById(editId),data,{updatedAt:Date.now()})}else{state.library.push({id:uid(),favorite:false,timestamps:[],createdAt:Date.now(),...data})}save();$('#videoDialog').close();renderAll();toast('保存しました')}
function parseTimestampText(text){const out=[];for(const line of String(text).split(/\r?\n/)){const m=line.match(/(?:^|\s)(\d{1,2}:\d{2}(?::\d{2})?)(?:\s+|[-–—｜|:：]\s*)(.*)$/);if(!m)continue;const time=parseTime(m[1]);if(time==null)continue;let label=(m[2]||'').trim().replace(/^[-–—｜|:：]+\s*/,'');if(!label)label='タイムスタンプ';const tags=guessTags(label);out.push({time,label,tags})}return out.filter((v,i,a)=>a.findIndex(z=>z.time===v.time&&z.label===v.label)===i).sort((a,b)=>a.time-b.time)}
function guessTags(label){const rules=[['耳かき','耳かき'],['梵天','梵天'],['囁','囁き'],['吐息','吐息'],['オノマトペ','オノマトペ'],['タッピング','タッピング'],['マッサージ','マッサージ'],['添い寝','添い寝'],['睡眠','睡眠'],['右耳','右耳'],['左耳','左耳'],['両耳','両耳'],['交互','交互']];return rules.filter(([k])=>label.includes(k)).map(([,v])=>v)}
function openTimestampDialog(){state.parsedTimestamps=[];$('#timestampPaste').value='';$('#timestampPreview').innerHTML='';$('#parseSummary').textContent='';$('#saveTimestampsBtn').disabled=true;$('#timestampDialog').showModal()}
function showTimestampPreview(){const rows=state.parsedTimestamps;$('#parseSummary').textContent=`${rows.length}件検出しました`;$('#timestampPreview').innerHTML=rows.map((t,i)=>`<div class="preview-row"><input data-i="${i}" data-k="time" value="${fmt(t.time)}"><input data-i="${i}" data-k="label" value="${attr(t.label)}"></div>`).join('');$('#saveTimestampsBtn').disabled=!rows.length;$$('#timestampPreview input').forEach(el=>el.onchange=()=>{const i=Number(el.dataset.i);if(el.dataset.k==='time'){const n=parseTime(el.value);if(n!=null)state.parsedTimestamps[i].time=n}else{state.parsedTimestamps[i].label=el.value.trim()||'タイムスタンプ';state.parsedTimestamps[i].tags=guessTags(state.parsedTimestamps[i].label)}})}
function saveParsedTimestamps(){const x=itemById(state.selectedId);if(!x)return;x.timestamps=x.timestamps||[];for(const t of state.parsedTimestamps){const exists=x.timestamps.some(z=>z.time===t.time&&z.label===t.label);if(!exists)x.timestamps.push(t)}x.timestamps.sort((a,b)=>a.time-b.time);save();$('#timestampDialog').close();renderDetail();toast('タイムスタンプを追加しました')}
function playItem(id,start=0){const x=itemById(id);if(!x)return;state.currentId=id;state.recent=[id,...state.recent.filter(v=>v!==id)].slice(0,50);save();$('#miniThumb').src=thumb(x.videoId);$('#miniTitle').textContent=x.title;$('#miniCreator').textContent=x.creator||'配信者未設定';$('#volume').value=x.volume??35;if(state.player&&state.player.loadVideoById){state.player.loadVideoById({videoId:x.videoId,startSeconds:start});state.player.setVolume(x.volume??35)}else{toast('YouTubeプレイヤーを準備中です')}renderLibrary()}
function queue(){return filtered()}
function step(dir){const q=queue();if(!q.length)return;let i=q.findIndex(x=>x.id===state.currentId);i=i<0?0:(i+dir+q.length)%q.length;playItem(q[i].id)}
function updatePlayerUi(){if(!state.player?.getCurrentTime)return;const t=state.player.getCurrentTime()||0,d=state.player.getDuration()||0;state.duration=d;$('#timeNow').textContent=fmt(t);$('#timeTotal').textContent=fmt(d);if(d)$('#seek').value=Math.round(t/d*1000);if(state.loopA!=null&&state.loopB!=null&&t>=state.loopB)state.player.seekTo(state.loopA,true)}
function addToPlaylistPrompt(id){if(!state.playlists.length)return toast('先にプレイリストを作成してください');const names=state.playlists.map((p,i)=>`${i+1}: ${p.name}`).join('\n');const n=Number(prompt(`追加先の番号を入力してください\n${names}`));const p=state.playlists[n-1];if(!p)return;if(!p.items.includes(id))p.items.push(id);save();renderPlaylists();toast(`${p.name}に追加しました`)}
function exportJson(){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),library:state.library,playlists:state.playlists,recent:state.recent},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`asmrtube_backup_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function importJson(file){const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d.library))throw 0;state.library=d.library;state.playlists=Array.isArray(d.playlists)?d.playlists:[];state.recent=Array.isArray(d.recent)?d.recent:[];save();renderAll();toast('バックアップを読み込みました')}catch{toast('対応していないJSONです')}};r.readAsText(file)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function attr(s){return esc(s)}
window.onYouTubeIframeAPIReady=()=>{state.player=new YT.Player('ytPlayerHost',{height:'1',width:'1',videoId:'',playerVars:{playsinline:1},events:{onReady:e=>e.target.setVolume(35),onStateChange:e=>{$('#playBtn').textContent=e.data===YT.PlayerState.PLAYING?'❚❚':'▶'}}});setInterval(updatePlayerUi,500)};
$('#addVideoBtn').onclick=()=>openVideoDialog();$('#emptyAddBtn').onclick=()=>openVideoDialog();$('#videoForm').onsubmit=saveVideo;$('#filterBtn').onclick=()=>$('#filters').classList.toggle('hidden');$('#clearFiltersBtn').onclick=()=>{state.filters.clear();renderFilterChips();renderLibrary()};$('#searchInput').oninput=e=>{state.query=e.target.value.trim();renderLibrary()};$('#sortSelect').onchange=renderLibrary;$$('.nav-btn').forEach(b=>b.onclick=()=>{state.currentView=b.dataset.view;state.currentPlaylist=null;$$('.nav-btn').forEach(n=>n.classList.toggle('active',n===b));const map={all:['ASMRライブラリ','登録したASMRをすぐ探して再生できます'],favorites:['お気に入り','お気に入りにしたASMR'],recent:['最近聴いた','直近に再生したASMR'],sleep:['睡眠向け','寝落ち向けに登録したASMR']};[$('#viewTitle').textContent,$('#viewSub').textContent]=map[state.currentView];renderPlaylists();renderLibrary()});$('#parseTimestampsBtn').onclick=()=>{state.parsedTimestamps=parseTimestampText($('#timestampPaste').value);showTimestampPreview()};$('#saveTimestampsBtn').onclick=saveParsedTimestamps;$('#newPlaylistBtn').onclick=()=>{$('#playlistName').value='';$('#playlistDialog').showModal()};$('#playlistForm').onsubmit=e=>{e.preventDefault();const name=$('#playlistName').value.trim();if(!name)return;state.playlists.push({id:uid(),name,items:[]});save();$('#playlistDialog').close();renderPlaylists();toast('プレイリストを作成しました')};$('#exportBtn').onclick=exportJson;$('#importInput').onchange=e=>{if(e.target.files[0])importJson(e.target.files[0]);e.target.value=''};$('#playBtn').onclick=()=>{if(!state.player)return;if(state.player.getPlayerState()===YT.PlayerState.PLAYING)state.player.pauseVideo();else state.player.playVideo()};$('#prevBtn').onclick=()=>step(-1);$('#nextBtn').onclick=()=>step(1);$('#volume').oninput=e=>{state.player?.setVolume(Number(e.target.value));const x=itemById(state.currentId);if(x){x.volume=Number(e.target.value);save()}};$('#seek').oninput=e=>{if(state.duration)state.player?.seekTo(Number(e.target.value)/1000*state.duration,true)};$('#loopBtn').onclick=()=>{if(!state.player)return;const t=state.player.getCurrentTime()||0;if(state.loopA==null){state.loopA=t;state.loopB=null;$('#loopBtn').textContent=`A ${fmt(t)}`;toast('A地点を設定しました')}else if(state.loopB==null){if(t<=state.loopA)return toast('B地点はAより後にしてください');state.loopB=t;$('#loopBtn').textContent='A-B ON';toast(`${fmt(state.loopA)}〜${fmt(state.loopB)} をリピート`)}else{state.loopA=state.loopB=null;$('#loopBtn').textContent='A-B';toast('区間リピートを解除しました')}};$('#sleepBtn').onclick=()=>$('#sleepDialog').showModal();$$('[data-sleep]').forEach(b=>b.onclick=()=>{clearTimeout(state.sleepTimer);const min=Number(b.dataset.sleep);if(min){state.sleepTimer=setTimeout(()=>{state.player?.pauseVideo();toast('スリープタイマーで停止しました')},min*60000);toast(`${min}分後に停止します`)}else toast('スリープタイマーを解除しました')});
load();renderAll();